
version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=3
      - HDFS_CONF_dfs_namenode_name_dir=file:///hadoop/dfs/name

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    depends_on:
      - namenode

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    restart: always
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    depends_on:
      - namenode

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    restart: always
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    depends_on:
      - namenode

  datanode4:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode4
    restart: always
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
    volumes:
      - hadoop_datanode4:/hadoop/dfs/data
    depends_on:
      - namenode

  datanode5:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode5
    restart: always
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
    volumes:
      - hadoop_datanode5:/hadoop/dfs/data
    depends_on:
      - namenode

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    ports:
      - 8088:8088
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - YARN_CONF_yarn_nodemanager_aux_services=mapreduce_shuffle
      - YARN_CONF_yarn_resourcemanager_resource_tracker_address=resourcemanager:8025
      - YARN_CONF_yarn_resourcemanager_scheduler_address=resourcemanager:8030
      - YARN_CONF_yarn_resourcemanager_address=resourcemanager:8040
      - YARN_CONF_yarn_resourcemanager_admin_address=resourcemanager:8050
      - HDFS_CONF_dfs_replication=1
    depends_on:
      - namenode

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - YARN_CONF_yarn_nodemanager_aux_services=mapreduce_shuffle
    depends_on:
      - resourcemanager

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
      - MAPRED_CONF_mapreduce_jobhistory_address=historyserver:10020
      - MAPRED_CONF_mapreduce_jobhistory_webapp_address=historyserver:19888
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    ports:
      - 19888:19888
    depends_on:
      - namenode
      - resourcemanager
      - nodemanager

  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      - POSTGRES_DB=metastore
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
    - ./postgres-data:/var/lib/postgresql/data

  hive-metastore:
    image: apache/hive:4.0.0
    container_name: hive-metastore
    restart: always
    ports:
      - 9083:9083
    environment:
      HIVE_METASTORE_URIS: thrift://hive-metastore:9083
      HADOOP_CLASSPATH: /opt/hive/lib/postgresql-42.5.1.jar
      HIVE_AUX_JARS_PATH: /opt/hive/lib/postgresql-42.5.1.jar
      HIVE_METASTORE_DB_TYPE: postgres
      HIVE_METASTORE_DB_URI: jdbc:postgresql://postgres:5432/metastore
      HIVE_METASTORE_DB_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_DB_USER: admin
      HIVE_METASTORE_DB_PASSWORD: admin
    depends_on:
      - postgres
    volumes:
      - ./hive-site.xml:/opt/hive/conf/hive-site.xml
      - ./lib:/opt/hive/lib
      - ./hive-scripts/postgres/hive-schema-4.0.0.postgres.sql:/opt/hive/scripts/hive-schema-4.0.0.postgres.sql
    command: bash -c "export CLASSPATH=\$CLASSPATH:/opt/hive/lib/* && /opt/hive/bin/schematool -initSchema -dbType postgres -verbose && hive --service metastore"

  hive-server:
    image: apache/hive:4.0.0
    container_name: hive-server
    restart: always
    depends_on:
      - hive-metastore
    ports:
      - 10000:10000
    environment:
      HIVE_METASTORE_URIS: thrift://hive-metastore:9083
      HADOOP_CLASSPATH: /opt/hive/lib/postgresql-42.5.1.jar
      HIVE_AUX_JARS_PATH: /opt/hive/lib/postgresql-42.5.1.jar
      HIVE_METASTORE_DB_TYPE: postgres
      HIVE_METASTORE_DB_URI: jdbc:postgresql://postgres:5432/metastore
      HIVE_METASTORE_DB_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_DB_USER: admin
      HIVE_METASTORE_DB_PASSWORD: admin
    volumes:
      - ./hive-site.xml:/opt/hive/conf/hive-site.xml
      - ./lib:/opt/hive/lib
      - ./hive-scripts/postgres/hive-schema-4.0.0.postgres.sql:/opt/hive/scripts/hive-schema-4.0.0.postgres.sql
    command: bash -c "export CLASSPATH=\$CLASSPATH:/opt/hive/lib/* && hive --service hiveserver2"

  spark:
    image: bitnami/spark:latest
    container_name: spark
    user: root
    depends_on:
      - namenode
      - resourcemanager
      - nodemanager
      # - hive-server
    environment:
      - SPARK_MODE=master
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_LOG_LEVEL=INFO
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
      - YARN_CONF_DIR=/opt/hadoop/etc/hadoop
      - IVY_HOME=/ivy2
      - SPARK_LOCAL_DIRS=/tmp/spark-local
      - SPARK_SUBMIT_OPTS="-Dspark.jars.ivy=/ivy2 -Dspark.local.dir=/tmp/spark-local -Divy.cache.dir=/ivy2 -Divy.local.dir=/ivy2"
      - PATH=/opt/bitnami/python/bin:/opt/bitnami/java/bin:/opt/bitnami/spark/bin:/opt/bitnami/spark/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./hadoop-config:/opt/hadoop/etc/hadoop
      - ./ml_task.py:/opt/spark/ml_task.py
    entrypoint: ["sh", "-c", "apt-get update && apt-get install -y python3-pip && pip3 install pandas scikit-learn pyspark && python3 /opt/spark/ml_task.py && tail -f /dev/null"]

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_datanode4:
  hadoop_datanode5:
